language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install .
- pip install -r requirements-dev.txt
script: py.test
notifications:
  email: false
deploy:
  provider: pypi
  user: ybon
  password:
    secure: 4jLqAHZaQoagbNQykk6HO6TFUL0DDnlN/wxHqURJKTSnQsQToptHLY1P69CEAAlxJ8s0OcVMBeV3Qh5BiUMnDq9JLCLcub86OXd0vpt9LYrkbico1niAWNNbmu1FqF8wI6qmnV2PLj44LVn/mFlj3SoZ2RDiz0Ke+xOVKvonTRVPfLxijnXQYX1KOpSwqYpcqJfHQaVYWy/Y1AEAPEaVkjWt1Ho5GwWdmZAC6+K3AcdyMGiiK64ZA7y6SGWEf86qC4rmb9LRh7IO2sy9c4ESzjW3pig53BhENtRNyvWgXmqo43ekItcIT/IYGTbsstokG7NZ934zoOH8IA9y0p9CsjzURs58o5lBe5kuXR29yJ6w94X6B48a1lSXMCi9A3RQwW+TJIv/Zxp1sV/dGjmAOPzVua/G60QIY0p/fPCXP3QgWGi74Z+w7V8x3qnVZO4kVisjeHK9owKrQg54ziezq1AFbtTPSF1Ob14ToEy1b7bfdywDTe2pUWQJHG8IUUnnHtERXKAAoC06kDyH81wtTipj4KGpUBVV8VLXqq5tX7phLyVfQOuxkBQvAHkkZPknJ4LyAKdjI0VtilUc1+JpqkcIyri9ofogkIzKbTgdr4bkisBdF2FYnYUrUScM1BT8mObFBsPrjp71UvTHPb6H+Glay4gj4kq4TUAr7la8hEA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: yohanboniface/falcon-multipart
